title: Ivan Arias Blog 
author:
  name: Ivan Arias
  email: arias.ivan@hcoco1.com
  twitter: hcoco1
  github: hcoco1

twitter:
  username: hcoco1
  card: summary

description: >
  This site serves as a platform to chronicle my adventures and expertise as a Software Engineer Student. Diving deep into the realm of Full Stack Development, I will be sharing my experiences and knowledge with the world.
# Build settings
theme: minima
logo: /assets/images/logo.png
tagline: Ivan Arias Blog | This Site is dedicated to share my knowledge and experience in the software development world. 
lang: en # Assuming your site is primarily in English

social:
  name: Ivan Arias
  links:
    - https://twitter.com/hcoco1
    - https://www.linkedin.com/in/hcoco1
    - https://github.com/hcoco1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO Enhancements
permalink: /:title/

excerpt_separator: "<!--more-->"


# Theme-specific settings
minima:
  skin: auto
  social_links:
    - { platform: devto,          user_url: "https://dev.to/hcoco1" }
    - { platform: github,         user_url: "https://github.com/hcoco1" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/hcoco1" }
    - { platform: twitter,        user_url: "https://twitter.com/hcoco1" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@hcoco1/videos" }

# Disqus Comments
disqus:
  shortname: hcoco1

url: https://hcoco1-blog.onrender.com
